# Project information
site_name: Workshop "Getting started with multi tenancy"
site_url: https://thomassuedbroecker.github.io/ce-cns-multi-tenant/
site_author: Thomas Suedbroecker

# Repository
repo_name: Multi Tenancy - Cloud-Native-Starter
repo_url: https://github.com/thomassuedbroecker/ce-cns-multi-tenant.git
edit_uri: edit/master/documentation
docs_dir: documentation

# Navigation
nav:
  - App ID discovery frontend : details-appid-fronted-vuejs.md
  - Compare App ID and Keycloak : compare-appid-keycloak.md
  - Introduction:
    - Overview: ./README.md
  - Implementation details:
    - Vue.js extract domain from email: details-email-domain.md 
    - Quakus extract tenant and reconfigure OIDC configuration: details-quarkus-extract-tenant.md
    - Setup AppID service: setup-appid.md
  - Labs: 
    - 1. TBD: ./lab-tbd.md
  - Optional Labs: 
    - 1. TBD: ./optional-lab-tbd.md
  - Additional Resources:
    - Cloud Native Starter example:
       - Cloud-Native-Starter project: https://github.com/IBM/cloud-native-starter
       - Cloud-Native-Starter project security: https://github.com/IBM/cloud-native-starter/security
       - Keycloak core concepts of open-source identity and access management: https://developers.redhat.com/blog/2019/12/11/keycloak-core-concepts-of-open-source-identity-and-access-management/
    - IBM CLoud Code Engine:
       - Examples on GitHub: https://github.com/IBM/CodeEngine
       - Code Engine CLI reference: https://cloud.ibm.com/docs/codeengine?topic=codeengine-cli

## DO NOT CHANGE BELOW THIS LINE

# Copyright
# copyright: Copyright &copy; 2020 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    # .svg automatically appended
    #logo: ibm_8bar_reverse_2
    logo: material/library
  # enable if you want to use a custom icon
  # custom_dir: overrides
  features:
    # - navigation.tabs
    - navigation.instant
    # - navigation.expand
  # palette:
  #  scheme: default
  #  primary: black
  #  accent: blue
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
